### ISSUE TITLE
Map data

### ISSUE THREAD

**Issue by pboutin** [brather1ng/RePoE#10]
Hello !

Would it be possible to load map information from PyPoE ?

I played with the `AtlasNode` exporter but I don't quite understand the output (bunch of ids).

Currently, I'm using a web scraper that crawl the wiki but since the Atlas have been updated frequently in the past leagues, it is not longer a viable option (always outdated).
source: https://github.com/poe-world/poe-world-resources/blob/master/maps.json

If it's doable, I'd be willing to help writing it !

**Comment by brather1ng** [comment]
What kind of information from the linked file do you need?

If it's just the names and tiers of maps, it should be pretty simple.

If you want information like the position on the atlas, it should be possible to load that with PyPoE because the game client needs it. However, I haven't messed with that kind of information, so I have no idea in which dat files it might be located.

If you need information like divination card drops, I'm pretty sure you can't get it through PyPoE. Those are manually maintained in the wiki.

**Comment by pboutin** [comment]
I guess I could have an hybrid solution,

- Having as much info as possible from the game itself
- Scraping _bonus_ information from the wiki

So let's say I want the names and tiers, would a `maps.json` belongs here ?
If so, what the best way I can get it done ?

Thanks for the quick reply, Exile :)

**Comment by brather1ng** [comment]
You might get some of the very basic information into base_items.json by just allowing maps to appear there (add "Maps" to `ITEM_CLASS_WHITELIST` in `RePoE/base_items.py`). base_itemsshould be the most suitable place for most of the information you can get from the game data (at least name, area level and tier), though I'm not sure where area level and tier are stored. If you find the file for that, you can get the relevant row from that table in `base_items.py` as done with the other item types, e.g. armour and flasks.

For everything else, I have no idea where the information is stored (if it's even available). PyPoE's GGPK viewer and the dat specification (https://github.com/OmegaK2/PyPoE/blob/dev/PyPoE/poe/file/specification/data/stable.py) might be useful to find that out. If it's only simple fields like the atlas offsets, I'd say that can also go into the base_items file. If it's more than that, a separate file might make sense.

Also, you can maybe get your stuff from the wiki API so you don't need to do HTML scraping.

**Comment by brather1ng** [comment]
`base_items.json` now has maps, but without any additional map-specific information. If there's anything additional you need, feel free to reopen this (and specify what you need).
