### ISSUE TITLE
Please add path-of-exile topic to github project

### ISSUE THREAD

**Issue by NelsonMinar** [brather1ng/RePoE#11]
Thanks for RePoE! A minor request; could you add the "path-of-exile" topic to your project in GitHub? That will make it visible from this page, which is the top Google hit for poe and github: https://github.com/topics/path-of-exile

Instructions on adding GitHub topics are here. It's very easy, but you have to be the project owner: https://help.github.com/en/articles/classifying-your-repository-with-topics

**Comment by brather1ng** [comment]
Done, thanks!
