### ISSUE TITLE
Missing Prophecies and Divination Cards in base_items

### ISSUE THREAD

**Issue by SunBlade-ger** [brather1ng/RePoE#13]
as far as i can tell base_items is missing:
- Prophecies
- Divination Cards

is that another problem with ITEM_CLASS_WHITELIST ?
or did i overlook them, because they share the same base item?

**Comment by brather1ng** [comment]
Prophecies share the same base item: `Metadata/Items/Currency/CurrencyItemisedProphecy`

I've added Divination Cards, they weren't in `ITEM_CLASS_WHITELIST`.
