### ISSUE TITLE
Duplicates in the data

### ISSUE THREAD

**Issue by newicz** [brather1ng/RePoE#14]
Hey!

I have noticed that there are duplicates in the data, specifically `gems.min.json` seems to have those. I have noticed that base_item id is null for the duplicate.

What I did:

Basically load the gems file and run simple js to check the structure on a single gem:
```
Object.keys(gems).forEach((key) => {
      if (key.includes('AbyssalCry')) {
            console.log(gems[key])
      }
})
```
Imagine how surprised I was when I noticed two console logs. Then I made the screenshot to show you in console how it looks like:

![Screen Shot 2019-10-14 at 14 52 42](https://user-images.githubusercontent.com/598673/66752917-e2d8b680-ee92-11e9-8a0c-368e8570111f.png)

Do you know why this is happening? 
I can write myself a cleanup script that will throw all the duplicates, but just wonder what is the reason they are there, maybe I'm missing something?

**Comment by brather1ng** [comment]
If you look at the full key, it kind of explains itself: `AbyssalCry` and `AbyssalCryTriggered`. GGG tends to create duplicates for item-inherent skills

**Comment by newicz** [comment]
Ohh, so they are just representants of GEM but provided by an item like "Grants level 20 Abyssal Cry skill" or something like that?

**Comment by brather1ng** [comment]
Exactly
