### ISSUE TITLE
Spawn weight and Generation weight

### ISSUE THREAD

**Issue by andreandersen** [brather1ng/RePoE#2]
Hi,

Would it be possible to add spawn weight and generation weight on the mods data?

**Comment by brather1ng** [comment]
Yes, definitely! Should also be fairly simple, I'm already processing the spawn weights anyway.

**Comment by andreandersen** [comment]
I just wrote my first lines of python, and I'm sure it's awful. Here's my suggestion however:
https://github.com/andreandersen/RePoE/commit/2d91025fc3e593c502b5eb49e4a19e147a6806f3

**Comment by brather1ng** [comment]
I'll probably change the json layout for those a bit to be generally more extensible (so changes after this don't break existing code), something like this:

```json
{
  "id": "helmet",
  "can_spawn": true,
  "weight": 1000
}
```

But other than that it would be pretty much what you did.

Not sure when I'll get around to it, you'll probably have to wait a few days.

**Comment by andreandersen** [comment]
Actually, to be fair a dictionary/hash would be faster codewise to consume than an array, so something like the following would make a lot of sense _to me_ at least. 
```javascript
{
    /// ...
    "spawn_tags": {
        "helmet" : {
            "can_spawn": true,
            "weight": 1000
        }
    }
}
```

Either would work of course, just map it after deserialization.

**Comment by brather1ng** [comment]
The thing is, the order of the elements important, which is lost in a dictionary. That can easily be seen if you look at "default" being the last entry most of the time, which matches every single item.

**Comment by andreandersen** [comment]
I'm not sure why the order of the elements would be important to you, but by all means :)

**Comment by brather1ng** [comment]
The order is not just important to me, it's necessary to do anything useful with mod crafting. Take a look at a bit larger example:

```json
  "AddedColdDamage1": {
    "spawn_tags": [
      {
        "no_attack_mods": false
      },
      {
        "ring": true
      },
      {
        "amulet": true
      },
      {
        "quiver": true
      },
      {
        "gloves": true
      },
      {
        "default": false
      }
    ],
  }
```

Now you have an item with the Tags `no_attack_mods`, `ring` and `default` (any ring with "Cannot roll Attack mods" crafted onto it). Without order, you have one tag that says the mod can spawn and two that say it can't, how would you determine which one of the three spawn tags/weights applies? You could probably create rules for tag priority, but at that point it's easier to just keep them ordered and take the first match.
