### ISSUE TITLE
Mods documentation - tag example

### ISSUE THREAD

**Issue by AlsoInteresting** [brather1ng/RePoE#25]
The AddedChaosDamageCorrupted1 doesn't have ring weight of 1000 anymore. Maybe change the example?

**Comment by AlsoInteresting** [comment]
Can I ask you a question through mail?
My problem in understanding isn't an issue with the project.

The mod AbyssAddedFireDamageWithSwordsJewel4 is from domain abyss_jewel and has translation "Adds (12 - 13) to (20 - 22) Fire Damage to Sword Attacks".
This mod carries the tag "sword" but doesn't exist on any POE affix site it seems.
So I'm missing something here.
Is this domain legacy?

Kind regards


________________________________
Van: Sören Thomas <notifications@github.com>
Verzonden: vrijdag 1 mei 2020 9:16
Aan: brather1ng/RePoE <RePoE@noreply.github.com>
CC: AlsoInteresting <adriaanbogaerts@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [brather1ng/RePoE] Mods documentation - tag example (#25)


Closed #25<https://github.com/brather1ng/RePoE/issues/25> via ed99add<https://github.com/brather1ng/RePoE/commit/ed99add79452174376a802cbe8f40ebe15bef993>.

**Comment by brather1ng** [comment]
It does seem to exist on items, see https://www.pathofexile.com/trade/search/Delirium/LB9QDp5tn. Not sure why affix sites don't list it.

Responding to issue mails just adds a comment to the issue, btw.

**Comment by AlsoInteresting** [comment]
Thanks.
Also thanks for all the effort you have put in.

Btw: some links in https://github.com/brather1ng/RePoE/blob/master/RePoE/docs/base_items.md don't work anymore.

________________________________
Van: Sören Thomas <notifications@github.com>
Verzonden: woensdag 6 mei 2020 14:53
Aan: brather1ng/RePoE <RePoE@noreply.github.com>
CC: AlsoInteresting <adriaanbogaerts@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [brather1ng/RePoE] Mods documentation - tag example (#25)


It does seem to exist on items, see https://www.pathofexile.com/trade/search/Delirium/LB9QDp5tn. Not sure why affix sites don't list it.

Responding to issue mails just adds a comment to the issue, btw.
