### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by AlsoInteresting** [brather1ng/RePoE#26]
- So tags in add_tags always have a spawn_weight > 0?

- Some modifiers don't have any tags with spawn_weight > 0 but do have add_tags.
Like AttackSpeedCorrupted. They can spawn?

- It is not always clear on what item a modifier can spawn.
A tag like "2h_mace_elder" is obvious but a tag like "has_caster_mod" isn't clear for me.
Does the tag "dex_armour" apply only to dex_helmet,dex_boots,dex_gloves,dex_body_armour or also dex_int_gloves?

**Comment by brather1ng** [comment]
> So tags in add_tags always have a spawn_weight > 0?

No, see e.g. "no_attack_mods", added by IntMasterItemGenerationCannotRollAttackAffixes.

> Some modifiers don't have any tags with spawn_weight > 0 but do have add_tags. Like AttackSpeedCorrupted. They can spawn?

They can't spawn through normal means, but they can e.g. be crafted (DexMasterGlobalAttackSpeedCrafted1) and can then influence the spawning of further mods.

> It is not always clear on what item a modifier can spawn.

There are three ways that I know of from which an item can get tags:

1. From the base item. E.g. "dex_armour" can only be on an item of a base with exactly that tag. See `tags` in `base_items.json` for that.
2. From the item being influenced. E.g. "2h_mace_elder" is the tag added to elder influenced 2h maces. See `item_classes.json` for the tags provided by influences on items of each item class.
3. From other mods that are already on the item. E.g. "has_caster_mod" is added by a bunch of mods. That's what `adds_tags` in `mods.json` is for.

**Comment by AlsoInteresting** [comment]
I'm trying to link item classes to their possible modifiers, spawned/corrupted/enchanted/..
Now I understand I have to match the tags from base_item.json with the ones (weight>0) in mods.json.
Thanks.

But then some of the tags in base_items.json don't match any tags in mods.json.
Like "amuletatlas2". 

Your example "IntMasterItemGenerationCannotRollAttackAffixes" doesn't have any spawn weights.
The added tag "no_attack_mods" tells me it cannot spawn on anything with Catarina's "Cannot roll Attack Mods".
So it can it be crafted on _any_ other gear?
(Beside items that have already mods of the same group)

If a stats id has a range 0-0, like on EnchantmentOfBladesOnHit4, it can't exist?
If I'm right, can you add it to the documentation?

**Comment by brather1ng** [comment]
> But then some of the tags in base_items.json don't match any tags in mods.json. Like "amuletatlas2".

Tags might be used for different things by the game, too. Or that's just something GGG added and never used.

> Your example "IntMasterItemGenerationCannotRollAttackAffixes" doesn't have any spawn weights.

It works the other way around. IntMasterItemGenerationCannotRollAttackAffixes *is* Catarina's "Cannot roll Attack Mods". If you craft it onto an item, that item gets the tag "no_attack_mods". That tag prevents a bunch of mods from spawning on items, as it's listed with a `spawn_weight` of 0 on them, see e.g. AccuracyRatingPerFrenzyChargeUber1.

Crafting mods onto gear ignores `spawn_weights`. For crafting options, see `crafting_bench_options.json`.

> If a stats id has a range 0-0, like on EnchantmentOfBladesOnHit4, it can't exist?

No idea what the game does there. Stats with value 0 have no effect either way.
