### ISSUE TITLE
Gem images

### ISSUE THREAD

**Issue by C1rdec** [brather1ng/RePoE#31]
I was wondering if images of gems can be harvested out of the GGPK.

**Comment by brather1ng** [comment]
They can be, but I haven't done anything like that. I suggest looking directly into [PyPoE](https://github.com/OmegaK2/PyPoE).

It's a bit out of scope for this repo, imo. At least I wouldn't develop it myself.

**Comment by C1rdec** [comment]
I mean this would be a great `resource for tool developers`. I'm myself a developer of [Poe Lurker](https://github.com/C1rdec/Poe-Lurker) and I'm already using this repo to get gem informations but I'm missing images... It would be awesome to have something with a name matching related to the gemId. I will look this up with PyPoE but I would love a helping hand. :blush:

**Comment by brather1ng** [comment]
Honestly, I have no idea how you'd get them out of PyPoE programmatically, so I wouldn't be of much help there. `base_items.visual_identity.dds_file` already provides the link to the file name. If someone does this and wants to add it to RePoE, I'd be open for it, but I wouldn't do it myself.

Also, images are a different thing than the game data currently in here, so I'd only add them with consent from GGG. Though that shouldn't be difficult to get as they are already available on other third party sites.

**Comment by C1rdec** [comment]
I manage to build a tool that harvest the ImageUrl for each Gem out of the Wiki .
