### ISSUE TITLE
missing niko in crafting_bench_options?

### ISSUE THREAD

**Issue by kevindevm** [brather1ng/RePoE#33]
title, why dont show niko sockets and colours?

**Comment by brather1ng** [comment]
`crafting_bench_options.json` currently only contains craftable *mods*. Niko sockets and colors aren't mods and represented differently in the corresponding dat file.

If you have a use for Niko's options, I can add them.

**Comment by kevindevm** [comment]
i would be cool if added, but only if u want obviously, i wanted the json to do a crafting bench like the game that why i asked cuz in the game it shows niko's recipes
