### ISSUE TITLE
3.13 Gems

### ISSUE THREAD

**Issue by C1rdec** [brather1ng/RePoE#37]
Any update regarding the new gems?

**Comment by brather1ng** [comment]
I'm waiting for the spec to be updated in PyPoE.

**Comment by BanditTech** [comment]
Eagerly awaiting the data dump :D

**Comment by C1rdec** [comment]
I guess PyPoe are having troubles?

**Comment by BanditTech** [comment]
it seems so, if you look at their github there are several issues with how the new file is handled. This all started when they changed the way the patch was downloaded

**Comment by brather1ng** [comment]
I've fixed the spec myself for now (OmegaK2/PyPoE#144), but that might not be as simple all the time.
