### ISSUE TITLE
Condition matching

### ISSUE THREAD

**Issue by beerett** [brather1ng/RePoE#4]
I'm creating a site that explores mods (specific to Elder/shaper at the moment),  I ran across an issue and I'm not sure if I'm clear on how conditions should be approached when there are multiple mods returned.  

I know you've mentioned that the first condition that matches should be the one to accept but I'm having some difficulty with 'base_chance_to_freeze_%'  .  I know which mod it's supposed to be but when match through the translations I get a few extra cases that have blank conditions or I get blank conditions with only 1 result.  How do you tell which ones to skip with zero conditions and which not to skip? 

If there's only one result I take it even if it has no conditions? (global_minimum_added_cold_damage_vs_chilled_or_frozen_enemies) is an example with one result and no conditions.  I hope I'm explaining this right, let me know.

```  
 { 
                        "condition" : [  {     },  { "min" : NumberInt(1)  }   ], 
                        "format" : [  "ignore",   "ignore"   ], 
                        "index_handlers" : [  [   ],  [   ]   ], 
                        "string" : "Always Freezes Enemies on Hit"
                    }, 
                    {
                       ....
                    }, 
                    {
                        "condition" : [
                            {
                                "max" : NumberInt(99), 
                                "min" : NumberInt(1)
                            }, 
                            {
                                "max" : NumberInt(0), 
                                "min" : NumberInt(0)
                            }
                        ], 
                        "format" : [
                            "#", 
                            "ignore"
                        ], 
                        "index_handlers" : [
                            [
                            ], 
                            [
                            ]
                        ], 
                        "string" : "{0}% chance to Freeze"
                    }
                ], 
                "ids" : [
                    "base_chance_to_freeze_%", 
                    "always_freeze"
                ]
            }
```

And the other

```
{
    "English": [
      {
        "condition": [
          {},
          {}
        ],
        "format": [
          "#",
          "#"
        ],
        "index_handlers": [
          [],
          []
        ],
        "string": "Adds {0} to {1} Cold Damage against Chilled or Frozen Enemies"
      }
    ],
    "ids": [
      "global_minimum_added_cold_damage_vs_chilled_or_frozen_enemies",
      "global_maximum_added_cold_damage_vs_chilled_or_frozen_enemies"
    ]
  }
```

**Comment by brather1ng** [comment]
If there are no min/max values for an id in its condition, the condition is always true.

In your first case, the only condition for the first entry is that "always_freeze" has a value >= 1. Everything else is unspecified. The second entry requires 1 <= "base_chance_to_freeze_%" <= 99 and "always_freeze" == 0.

The condition of your second case is empty, meaning it is always true.

**Comment by beerett** [comment]
If two id's are listed at the bottom of a list of conditions I have to pass both conditions correct? In the first example first condition set I get an auto pass on base_chance and then need to check for always_freeze, which doesn't exist in the mod I'm looking at -- So that one will fail.  I keep going down the list until I have auto pass for the always_freeze and a pass for min/max/etc on base_chance.   Is that right?

**Comment by brather1ng** [comment]
If you only have less stat ids to translate than there are ids listed in the translation, assume a value of 0 for the missing stat ids.
