### ISSUE TITLE
Update with Ultimatum league data

### ISSUE THREAD

**Issue by leMicin** [brather1ng/RePoE#45]
Hi, I have tried to install all dependencies to be able to get the data myself, but I kind of gave up. Is it possible to update the data with the new ultimatum league?

Thanks,
Contributor for Sidekick (https://github.com/domialex/Sidekick)

**Comment by brather1ng** [comment]
PyPoE's spec needs to be updated for Ultimatum to update the data. With PyPoE seeming to be abandoned and the spec changes being much more complex this time around, that's not easy to do. Would probably be easiest to copy the spec changed from somewhere else if a suitable place exist.

**Comment by leMicin** [comment]
Awesome thanks for the information.
