### ISSUE TITLE
Missing veiled mods

### ISSUE THREAD

**Issue by aang521** [brather1ng/RePoE#50]
The new mods which can only be obtained trough unveiling are missing like:
```
(120–139)% increased Physical Damage
(21–25)% chance to Impale Enemies on Hit with Attacks
```
```
+2 to Level of Socketed Support Gems
+(5–8)% to Quality of Socketed Support Gems
```

**Comment by aang521** [comment]
The mods are now included in the data, thanks!
But I noticed the domain of these mods is still unknown4 instead of veiled.

**Comment by brather1ng** [comment]
Should be fixed now

**Comment by aang521** [comment]
Thanks!
