### ISSUE TITLE
Gems update

### ISSUE THREAD

**Issue by C1rdec** [brather1ng/RePoE#51]
Hi I just want to know when 3.15 gems will be available and what's the future of this repo?

Is there some one that is currently maintaining or you are looking for contributors to update data every league?

**Comment by brather1ng** [comment]
Provided PyPoE keeps working without requiring major changes, I'm still maintaining this.

The 3.15 update can't happen before the game patch is available. I'll hopefully get the update done today or tomorrow.

**Comment by C1rdec** [comment]
I know I just wanted to confirm thanks :)
If you are looking for help I'm more than happy to contribute :)

**Comment by brather1ng** [comment]
Updating RePoE itself has rarely been much work. Thanks for the offer, though.

I'm more concerned that there'll be too many breaking changes for PyPoE for me to handle at some point. So someone picking up and maintaining PyPoE would help a lot.
