### ISSUE TITLE
Missing stat translations

### ISSUE THREAD

**Issue by xanthics** [brather1ng/RePoE#53]
The new mods are missing entries in https://github.com/brather1ng/RePoE/blob/master/RePoE/data/stat_translations.json

Example: `{'adds_tags': [], 'domain': 'item', 'generation_type': 'enchantment', 'generation_weights': [], 'grants_effects': [], 'group': 'SkillEnchantment', 'implicit_tags': ['resource', 'mana', 'aura'], 'is_essence_only': False, 'name': 'Enchantment Anger Reservation 1', 'required_level': 66, 'spawn_weights': [{'tag': 'helmet', 'weight': 0}, {'tag': 'default', 'weight': 0}], 'stats': [{'id': 'anger_mana_reservation_efficiency_-2%_per_1', 'max': -10, 'min': -10}], 'type': 'EnchantmentAngerReservationCost'}`

stats_translations only has the old entry for `anger_mana_reservation`

**Comment by brather1ng** [comment]
stat_translations aren't updated for 3.16 yet. The files have an issue somewhere that breaks PyPoE's parser. I didn't look into that yet.
