### ISSUE TITLE
Vitality and Clarity have wrong values

### ISSUE THREAD

**Issue by HepNuk** [brather1ng/RePoE#54]
All 3 different of Vitalities and Clarities have wrong value per level

See https://poedb.tw/us/Vitality  and https://poedb.tw/us/Clarity for real values.

Example for Vitality Level 1 Life Regeneration per second 
`/data/gems.json`
```json
"Vitality": {

...

    "per_level": {
      "1": {
        "required_level": 10,
        "reservations": {
          "mana_flat": 28
        },
        "stat_requirements": {
          "str": 22
        },
        "stats": [
          {
            "value": 600
          },
          {
            "value": 0
          },
          null
        ]
      },
      "2": {

...

        "stats": [
          {
            "value": 725
          },
          {
            "value": 1
          },
          null
        ]
      },
      "3": {

...

        "stats": [
          {
            "value": 977
          },
          {
            "value": 2
          },
          null
        ]
      },
      "4": {

...

        "stats": [
          {
            "value": 1184
          },
          {
            "value": 3
          },
          null
        ]
      },


... etc

```

**Comment by brather1ng** [comment]
The values in the game files are for the stat `base_life_regeneration_rate_per_minute`. To get to the values shown on PoEDB, you have to apply the index handlers from the stat translations. In this case the translation for `base_life_regeneration_rate_per_minute` from `stat_translations/aura_skill` (see the `stat_translation_file` field in `gems`) has the index handler `per_minute_to_per_second`.
