### ISSUE TITLE
Delve Resonators, Contracts and Quest Items are missing in base_items

### ISSUE THREAD

**Issue by SunBlade-ger** [brather1ng/RePoE#58]
I can't find them in base_items, so i think they are missing their entries in ITEM_CLASS_WHITELIST:
- Delve Resonators
- Quest Items
- Contracts

Since Contracts probably have only a single base item, i am not sure if i simply overlooked them.

**Comment by brather1ng** [comment]
added with 4cc64c0603a2a735fd81a479c0202952681f28cb
