### ISSUE TITLE
Unable to parse 3.20

### ISSUE THREAD

**Issue by ixmike88** [brather1ng/RePoE#62]
`C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk53.in:    54199 =>   262144 (0.00 seconds, 1562.24 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk54.in:    53575 =>   262144 (0.00 seconds, 1635.33 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk55.in:    53171 =>   262144 (0.00 seconds, 1588.75 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk56.in:    55762 =>   262144 (0.00 seconds, 646.95 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk57.in:    47654 =>   262144 (0.00 seconds, 849.74 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk58.in:    38054 =>   262144 (0.00 seconds, 997.50 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk59.in:    47120 =>   262144 (0.00 seconds, 892.56 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk60.in:    45725 =>   262144 (0.00 seconds, 959.53 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk61.in:    52718 =>   262144 (0.00 seconds, 898.06 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk62.in:    51735 =>   262144 (0.00 seconds, 812.60 MB/s)
C:\Users\Admin\AppData\Local\Temp\tmp11uuwhij\chunk63.in:    17078 =>    91779 (0.00 seconds, 799.47 MB/s)
 Done!
Traceback (most recent call last):
  File "c:\pypoe\PyPoE\poe\file\file_system.py", line 177, in get_file
    with open(os.path.join(self.root_path, path), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Program Files (x86)/Grinding Gear Games/Path of Exile\\Data/Stats.dat'`

Just me?

**Comment by brather1ng** [comment]
GGG removed the .dat files, have to switch to using .dat64. Since PyPoE doesn't support those and I'm not going to put in the work for that myself, RePoE will stay broken for now. I hope that I can easily switch to the wiki fork of PyPoE once it has .dat64 support implemented.
